# Generated by Django 3.0.8 on 2020-08-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='choice',
            new_name='choice_answer',
        ),
    ]
