# Generated by Django 3.0.8 on 2020-08-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200803_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
